name: test
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: TypeScript report
        uses: fersilva16/ts-report-action@1.1.0
        with:
          project: tsconfig.json
