name: test
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: TypeScript report
      uses: fersilva16/ts-report-action@1.1.0
      with:
        project: path/to/tsconfig.json
